### ISSUE TITLE
Installation of instant-markdown fails with connection error

### ISSUE THREAD

**Issue by bytesource** [suan/vim-instant-markdown#4]
Installation of instant-markdown failed due to a connection error:

```
sovonex@sovonex:~/Desktop/temp/chinese/dev/css$ npm -d install instant-markdown-d
npm info it worked if it ends with ok
npm info using npm@0.2.19
npm info using node@v0.4.9
npm info bundling for instant-markdown-d@0.0.3 [ 'https://suan@github.com/suan/Docter/tarball/master' ]
npm ERR! Error connecting to server https://suan/github.com/suan/Docter/tarball/master
npm ERR! Error installing https://suan@github.com/suan/Docter/tarball/master
npm ERR! install failed Error: ENOTFOUND, Domain name not found
npm ERR! install failed     at IOWatcher.callback (dns.js:74:15)
npm info install failed rollback
npm info uninstall [ 'instant-markdown-d@0.0.3' ]
npm info preuninstall instant-markdown-d@0.0.3
npm info uninstall instant-markdown-d@0.0.3
npm info auto-deactive not symlink
npm info postuninstall instant-markdown-d@0.0.3
npm info uninstall instant-markdown-d@0.0.3 complete
npm info install failed rolled back
npm ERR! Error: ENOTFOUND, Domain name not found
npm ERR!     at IOWatcher.callback (dns.js:74:15)
npm ERR! Report this *entire* log at <http://github.com/isaacs/npm/issues>
npm ERR! or email it to <npm-@googlegroups.com>
npm ERR! Just tweeting a tiny part of the error will not be helpful.
npm not ok
```

Is there something wrong with `https://suan/github.com/suan/Docter/tarball/master` at the moment?

Stefan

**Comment by clockworkpc** [comment]
For me, on Arch Linux (Manjaro)
```sh
❯ node -v
v14.17.0
```
When I try to install it:

```sh
❯ sudo npm -g install instant-markdown-d
npm WARN deprecated mathjax-node-page@3.2.0: This package has been archived. MathJax v3 provides equivalent functionality.
npm WARN deprecated highlight.js@9.18.5: Support has ended for 9.x series. Upgrade to @latest
npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
/home/alexanderg/.nvm/versions/node/v14.17.0/bin/instant-markdown-d -> /home/alexanderg/.nvm/versions/node/v14.17.0/lib/node_modules/instant-markdown-d/instant-markdown-d

> highlight.js@9.18.5 postinstall /home/alexanderg/.nvm/versions/node/v14.17.0/lib/node_modules/instant-markdown-d/node_modules/highlight.js
> node deprecated.js

node:internal/modules/cjs/loader:944
  throw err;
  ^

Error: Cannot find module '/home/alexanderg/.nvm/versions/node/v14.17.0/lib/node_modules/instant-markdown-d/node_modules/highlight.js/deprecated.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:941:15)
    at Function.Module._load (node:internal/modules/cjs/loader:774:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! highlight.js@9.18.5 postinstall: `node deprecated.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the highlight.js@9.18.5 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-05-24T20_34_45_272Z-debug.log
❯ npm config set registry http://registry.npmjs.org/
❯ sudo npm -g install instant-markdown-d
npm WARN deprecated mathjax-node-page@3.2.0: This package has been archived. MathJax v3 provides equivalent functionality.
npm WARN deprecated highlight.js@9.18.5: Support has ended for 9.x series. Upgrade to @latest
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
/home/alexanderg/.nvm/versions/node/v14.17.0/bin/instant-markdown-d -> /home/alexanderg/.nvm/versions/node/v14.17.0/lib/node_modules/instant-markdown-d/instant-markdown-d

> highlight.js@9.18.5 postinstall /home/alexanderg/.nvm/versions/node/v14.17.0/lib/node_modules/instant-markdown-d/node_modules/highlight.js
> node deprecated.js

node:internal/modules/cjs/loader:944
  throw err;
  ^

Error: Cannot find module '/home/alexanderg/.nvm/versions/node/v14.17.0/lib/node_modules/instant-markdown-d/node_modules/highlight.js/deprecated.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:941:15)
    at Function.Module._load (node:internal/modules/cjs/loader:774:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! highlight.js@9.18.5 postinstall: `node deprecated.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the highlight.js@9.18.5 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-05-24T20_35_15_407Z-debug.log
```
